### ISSUE TITLE
Pipewire or Wireplumber using 100% CPU after using Bluetooth microphone

### ISSUE THREAD

**Issue by murilosr** [pop-os/pipewire#20]
I saw the issue #3, but I think this is a different issue. Something changed in the last days (I started noticing on July 21st).

After I use the bluetooth microphone on Microsoft Teams (I tested with others softwares, like Google Meet on Google Chrome, but I coudn't reproduce) it changes the Headset Profile to Handsfree HSP/HFB codec mSBC (as it always had changed, and it wasn't bugging). When the call ended, the headset loses the connection and wireplumber starts to use 100% of CPU (I noticed because my notebook turned on all its coolers).

![Screenshot from 2022-07-22 10-25-56](https://user-images.githubusercontent.com/22528237/180451775-afe4bb90-c6e0-4558-b352-462a47468b62.png)

When I reset the services, the CPU normalize.
Command used to restart:
`systemctl --user restart wireplumber pipewire pipewire-pulse
`

-----
**Pipewire version**

```
pipewire --version
pipewire
Compiled with libpipewire 0.3.56
Linked with libpipewire 0.3.56
```

-----
**PopOs Version**

```
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
LOGO=distributor-logo-pop-os
```

-----
**Hardwares**

Headphone used: HyperX Cloud Mix (with bluetooth connection)

Profiles:
![Screenshot from 2022-07-22 10-35-26](https://user-images.githubusercontent.com/22528237/180451821-5eeb7d8b-3960-4396-8a4d-5c4c600aa256.png)

**Comment by mmstick** [comment]
May be worth reporting the issue to https://gitlab.freedesktop.org/pipewire/wireplumber
We're keeping in sync with upstream releases and debian packaging.

**Comment by mmstick** [comment]
I've linked a pull request that might fix it. It would be useful if you could test it to see if it works. When the package has been built, you can add the testing repository with

```
git clone https://github.com/pop-os/pop
./pop/scripts/apt add wireplumber
```

Remove the testing repository after the PR is merged or closed with

```
./pop/scripts/apt remove wireplumber
```

And log out after updating/downgrading the wireplumber packages.
