### ISSUE TITLE
Audio cuts off after a few seconds in Java applications

### ISSUE THREAD

**Issue by 0dinD** [pop-os/pipewire#25]
On Pop!_OS 22.04, audio cuts off after a few seconds in Java applications using the `javax.sound` API (but I'm guessing it's not necessarily unique to Java). I managed to track the issue down to this patch: https://github.com/pop-os/pipewire/blob/a3894c2ce5de9986febde814b6fd8f3ff8cb288d/debian/patches/alsa-type-pulse.patch.

Steps to reproduce:
- Use Pop!_OS 22.04 (which has the patch linked above).
- Download the Java Sound Demo from here: https://www.oracle.com/java/technologies/java-sound-api.html
- Extract the demo, start it with `java -jar JavaSoundDemo.jar`.
- Click "Start" to play the audio, observe that it gets cut off after a few seconds.
- Revert the patch linked above by modifying `/etc/alsa/conf.d/99-pipewire-default.conf`.
- Play the audio again, observe that the audio doesn't get cut off.

From what I was able to find, this is the reason why the patch was introduced: https://www.reddit.com/r/pop_os/comments/ulu47b/audio_in_davinci_resolve_will_be_fixed_in_next/

I believe this may also be related: https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2626

**Comment by pinkflames** [comment]
I know this is a lot to ask but it's very surprising that a file named 99-pipewire-default.conf actually makes pulse ALSA plugin the default one. Surely Pop!_OS could do better by installing a more appropriate file (either custom or the upstream PulseAudio one).

**Comment by 0dinD** [comment]
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/2626 was supposedly fixed (I haven't tested it), so updating PipeWire to `0.3.58` once it's released might fix this particular issue with Java.
