### ISSUE TITLE
Version bump request - 0.3.63

### ISSUE THREAD

**Issue by kostadinsh** [pop-os/pipewire#36]
Pipewire 0.3.63 has been released. Could you bump the version?

https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.63

**Comment by hojjatabdollahi** [comment]
I'm experiencing audio distortions recently (I think since the last update a month ago), I think 0.3.63 fixes it. Can we get the updated version please?

**Comment by mmstick** [comment]
Yeah. Certainly
