### ISSUE TITLE
Unable to create combined sink 

### ISSUE THREAD

**Issue by ChiefGyk3D** [pop-os/pipewire#40]
Originally I had the bug report over in https://github.com/pop-os/pop/issues/2790 but this is specific to Pipewire, and I think it would be most appropriate here. 

I keep getting error
```
pactl load-module module-combine-sink
Failure: No such entity
```

it looks as if the module isn't even loaded, and I don't even have the module-combine-stream module which is apparently what has been added in this most recent version of Pipewire
```
chiefgyk3d@Project-NOS:~$ pactl list short
1	libpipewire-module-rt	{
            nice.level    = -11
            #rt.prio      = 88
            #rt.time.soft = -1
            #rt.time.hard = -1
        }	
2	libpipewire-module-protocol-native		
3	libpipewire-module-profiler		
5	libpipewire-module-metadata		
7	libpipewire-module-spa-device-factory		
9	libpipewire-module-spa-node-factory		
11	libpipewire-module-client-node		
13	libpipewire-module-client-device		
15	libpipewire-module-portal		
16	libpipewire-module-access	{
            # access.allowed to list an array of paths of allowed
            # apps.
            #access.allowed = [
            #    /usr/bin/pipewire-media-session
            #]

            # An array of rejected paths.
            #access.rejected = [ ]

            # An array of paths with restricted access.
            #access.restricted = [ ]

            # Anything not in the above lists gets assigned the
            # access.force permission.
            #access.force = flatpak
        }	
17	libpipewire-module-adapter		
19	libpipewire-module-link-factory		
21	libpipewire-module-session-manager		
28	libpipewire-module-x11-bell	{
            #sink.name = ""
            #sample.name = "bell-window-system"
            #x11.display = null
            #x11.xauthority = null
        }	
536870912	module-always-sink		
50	alsa_output.pci-0000_0a_00.1.hdmi-stereo-extra2	PipeWire	s32le 2ch 48000Hz	SUSPENDED
51	alsa_output.usb-R__DE_R__DECaster_Pro_II_GV0039166-00.iec958-stereo	PipeWire	s24le 2ch 48000Hz	SUSPENDED
53	alsa_output.pci-0000_0c_00.4.iec958-stereo	PipeWire	s32le 2ch 48000Hz	SUSPENDED
50	alsa_output.pci-0000_0a_00.1.hdmi-stereo-extra2.monitor	PipeWire	s32le 2ch 48000Hz	SUSPENDED
51	alsa_output.usb-R__DE_R__DECaster_Pro_II_GV0039166-00.iec958-stereo.monitor	PipeWire	s24le 2ch 48000Hz	SUSPENDED
52	alsa_input.usb-R__DE_R__DECaster_Pro_II_GV0039166-00.iec958-stereo	PipeWire	s24le 2ch 48000Hz	SUSPENDED
53	alsa_output.pci-0000_0c_00.4.iec958-stereo.monitor	PipeWire	s32le 2ch 48000Hz	SUSPENDED
54	alsa_input.pci-0000_0c_00.4.analog-stereo	PipeWire	s32le 2ch 48000Hz	SUSPENDED
32	PipeWire	xdg-desktop-portal
33	PipeWire	pipewire
34	PipeWire	firefox-bin
36	PipeWire	wireplumber
37	PipeWire	wireplumber
73	PipeWire	gnome-shell
74	PipeWire	gsd-media-keys
124	PipeWire	gnome-shell
172	PipeWire	pactl
0	bell-window-system	s16le 2ch 44100Hz	1.000
43	alsa_card.pci-0000_0a_00.1	alsa
44	alsa_card.usb-R__DE_R__DECaster_Pro_II_GV0039166-00	alsa
45	alsa_card.pci-0000_0c_00.4	alsa
```

There's a possibility looking at this, it may not have even been built with the package https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/fba7083f8ceb210c7c20aceafeb5c9a8767cf705

But based on this info it should definitely be included and working. 
https://gitlab.freedesktop.org/pipewire/pipewire/-/releases/0.3.65
https://www.phoronix.com/news/PipeWire-0.3.65-Released

**Comment by mmstick** [comment]
Then it should be fixed in the next PipeWire release that should be tagged soon.

**Comment by ChiefGyk3D** [comment]
It's not actually tagged for any release currently @mmstick right now as I have been told. 

"Yes. This commit is not part of any release, so distributions have to backport it or wait for a new release."
https://gitlab.freedesktop.org/pipewire/pipewire/-/issues/3025

I think this is a minor enough change that's breaking enough things for creatives on Pop!_OS it should maybe be looked at backporting to expedite a fix. I literally have the new Pangolin in my hand I am trying to get ready to do reviews live on Twitch, and eventually YouTube for the gaming performance as well as my general thoughts, and I actually can not properly route the audio as needed for my streams to work as I have been doing for months out of the box on this brand new laptop by System76. 

There's a lot of content for example I can't manually route properly through Helvum or Carla as it keeps creating new sources I have to manually route each time. So I would have to pause what I am doing just to create a new manual route, that may possibly have to be completely reconfigured a few minutes later. 

It looks to be only one line that actually needs to be changed, and I don't honestly think we can just wait around for Pipewire to release the official fix, especially when I am trying to do a product review. Please see #41

**Comment by mmstick** [comment]
They tag a new release every ~2-3 weeks, and it's already been 2 weeks since the last release was tagged, so the next release should be tagged soon. Either way, we can't merge anything without a pass through the QA checklist on Monday.

**Comment by ChiefGyk3D** [comment]
Ok I understand @mmstick but just a heads up I can't even do a manual work around with Helvum or Carla, because if I play any game, as soon as I click out of the game window to try piping it to multiple sources the actual game source disappears as the audio is no longer active, and generates a whole new process for the audio it seems. So at present any attempts at content creation on Pop!_OS are broken.

**Comment by ChiefGyk3D** [comment]
Is there any way I can possibly roll back to an earlier version of Pipewire I know was working? I can't seem to figure it out with apt as it throws too many errors
