### ISSUE TITLE
Audio stop working after pipewire 0.3.69 update

### ISSUE THREAD

**Issue by oscardoso** [pop-os/pipewire#50]
**Distribution (run `cat /etc/os-release`):**

 NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
VERSION_CODENAME=jammy
UBUNTU_CODENAME=jammy
 
 
**Related Application and/or Package Version (run `apt policy $PACKAGE NAME`):**

**pipewire:**
  Installed: 0.3.69\~1681911033\~22.04\~bb4229c
  Candidate: 0.3.69\~1681911033~22.04\~bb4229c
  Version table:
 *** 0.3.69\~1681911033\~22.04\~bb4229c 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.3.48-1ubuntu3 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/main amd64 Packages
     0.3.48-1ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages

**pipewire-pulse:**
  Installed: 0.3.69\~1681911033\~22.04\~bb4229c
  Candidate: 0.3.69\~1681911033\~22.04\~bb4229c
  Version table:
 *** 0.3.69\~1681911033\~22.04\~bb4229c 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.3.48-1ubuntu3 500
        500 http://apt.pop-os.org/ubuntu jammy-updates/universe amd64 Packages
     0.3.48-1ubuntu1 500
        500 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages

**wireplumber:**
  Installed: 0.4.13-1pop0\~1672359816\~22.04\~1185bca
  Candidate: 0.4.13-1pop0\~1672359816\~22.04\~1185bca
  Version table:
 *** 0.4.13-1pop0\~1672359816\~22.04\~1185bca 1001
       1001 http://apt.pop-os.org/release jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     0.4.8-4 500
        500 http://apt.pop-os.org/ubuntu jammy/universe amd64 Packages

**alsa-base:**
  Installed: 1.0.25+dfsg-0ubuntu7
  Candidate: 1.0.25+dfsg-0ubuntu7
  Version table:
 *** 1.0.25+dfsg-0ubuntu7 500
        500 http://apt.pop-os.org/ubuntu jammy/main amd64 Packages
        500 http://apt.pop-os.org/ubuntu jammy/main i386 Packages
        100 /var/lib/dpkg/status

**Issue/Bug Description:**

Since the last update I did (2023/04/19), It stopped having audio.

**Steps to reproduce (if you know):**

Turn on the computer, login. that's it!

**Expected behavior:**

Audio output and input.

**Other Notes:**

I looked in the issues section for similar solutions.

I tried everything described on this page: [System76 - Audio Troubleshooting](https://support.system76.com/articles/audio/l)

`aplay -l`
**** List of PLAYBACK Hardware Devices ****
card 0: HDMI [HDA ATI HDMI], device 3: HDMI 0 [24G2W1G4]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: Generic [HD-Audio Generic], device 0: ALC236 Analog [ALC236 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: Loopback [Loopback], device 0: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice pop-os/pop#1: subdevice pop-os/pop#1
  Subdevice pop-os/pop#2: subdevice pop-os/pop#2
  Subdevice pop-os/pop#3: subdevice pop-os/pop#3
  Subdevice pop-os/pop#4: subdevice pop-os/pop#4
  Subdevice pop-os/pop#5: subdevice pop-os/pop#5
  Subdevice pop-os/pop#6: subdevice pop-os/pop#6
  Subdevice pop-os/pop#7: subdevice pop-os/pop#7
card 2: Loopback [Loopback], device 1: Loopback PCM [Loopback PCM]
  Subdevices: 8/8
  Subdevice #0: subdevice #0
  Subdevice pop-os/pop#1: subdevice pop-os/pop#1
  Subdevice pop-os/pop#2: subdevice pop-os/pop#2
  Subdevice pop-os/pop#3: subdevice pop-os/pop#3
  Subdevice pop-os/pop#4: subdevice pop-os/pop#4
  Subdevice pop-os/pop#5: subdevice pop-os/pop#5
  Subdevice pop-os/pop#6: subdevice pop-os/pop#6
  Subdevice pop-os/pop#7: subdevice pop-os/pop#7

<hr />

`lspci -v | grep -A6 Audio`
00:01.1 Audio device: Advanced Micro Devices, Inc. [AMD/ATI] Device 15b3
        Subsystem: Lenovo Device 3805
        Flags: bus master, fast devsel, latency 0, IRQ 39
        Memory at f0e60000 (64-bit, non-prefetchable) [size=16K]
        Capabilities: <access denied>
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel

00:09.0 Host bridge: Advanced Micro Devices, Inc. [AMD] Carrizo Audio Dummy Host Bridge
        Flags: fast devsel

00:09.2 Audio device: Advanced Micro Devices, Inc. [AMD] Family 15h (Models 60h-6fh) Audio Controller
        Subsystem: Lenovo Family 15h (Models 60h-6fh) Audio Controller
        Flags: bus master, fast devsel, latency 0, IRQ 40
        Memory at f0e64000 (32-bit, non-prefetchable) [size=16K]
        Capabilities: <access denied>
        Kernel driver in use: snd_hda_intel
        Kernel modules: snd_hda_intel

<hr />

[ALSA information]( http://alsa-project.org/db/?f=b7cdf88f8a7aaf264000ec86c6b883615165525c)

**Comment by ghost** [comment]
A lot regression fixes again on upcoming https://github.com/pop-os/pipewire/pull/49 update.

**Comment by mmstick** [comment]
In the meantime, you can downgrade by adding the 0.3.68 repository:

```
sudo apt-manage add popdev:pipewire-0.3.68
sudo apt update
sudo apt full-upgrade
```

Remove it at a later time to upgrade

```
sudo apt-manage remove popdev-pipewire-0.3.68
```

**Comment by n3m0-22** [comment]
@oscardoso the update for [pipewire](https://github.com/pop-os/pipewire/pull/49) is now ready if you would like to check if it fixes your issue.

```
sudo apt-manage add popdev:pipewire-0.3.70
sudo apt update
sudo apt upgrade
reboot
```

**Comment by runboy93** [comment]
@n3m0-22 

I shared this test information with user on pop os reddit:

https://www.reddit.com/r/pop_os/comments/12stsc6/comment/jh3fett/

He had earlier "dummy output", but now after this test update it is working again!

https://i.vgy.me/JKVBef.png

**Comment by deviantgenome** [comment]
> @oscardoso the update for [pipewire](https://github.com/pop-os/pipewire/pull/49) is now ready if you would like to check if it fixes your issue.
> 
> ```
> sudo apt-manage add popdev:pipewire-0.3.70
> sudo apt update
> sudo apt upgrade
> reboot
> ```

Hi, I'm not @oscardoso but I've had the Dummy Output issue since the last Pipewire update and this [fixed it.](https://i.vgy.me/JKVBef.png)
I asked for support [here](https://www.reddit.com/r/pop_os/comments/12stsc6/dummy_output_is_the_only_output_device_available/) last night. 
Thanks to @runboy93 who brought your solution to my attention.

**Comment by oscardoso** [comment]
First of all thanks to everyone involved for being so quick!

@n3m0-22, I confirm that it fixed my problem.

**Comment by ObiWaz** [comment]
I am having a similar issue as OP. My audio deos not work in certain Steam games. This behavior started from an update last week. Someone on the PopOS subreddit suggested the fix above and it did not work. I noticed  that there was an update for pipewire today so I removed the "fix" and tried the update.  Still no dice.

**Comment by clebermasters** [comment]
[](url)Hello,
I am running the latest version 0.3.70 and PopOS 22.04, but my audio is not working.

Apr 30 11:47:29 pop-os systemd[2992]: Started PipeWire Multimedia Service.
Apr 30 11:47:39 pop-os pipewire[4587]: mod.rt: RTKit error: org.freedesktop.DBus.Error.InvalidArgs
Apr 30 11:47:39 pop-os pipewire[4587]: mod.rt: could not set nice-level to -11: Input/output error

Do we need to open a new issue? Or we can reopen this one? Can you help me?

**Comment by ghost** [comment]
I think they will release System76-Scheduler 2.0 very soon (they told something about monday update), there is something interesting for Pipewire (process priorities changes for audio/video servers and kernel auto-group feature disabled)

https://www.phoronix.com/news/System76-Scheduler-2.0

Try that and if still nothing for audio, then create new ticket but I would also recommend to do ticket to upstream:

https://gitlab.freedesktop.org/pipewire/pipewire

**Comment by clebermasters** [comment]
Thanks, RunBoy93. I opened a new issue on FreeDesktop. Also, I will keep watching this new release.

**Comment by clebermasters** [comment]
Just for an update. I have updated System76-Scheduler 2.0, but the audio doesn't work.
I have no trouble using USB headphones to listen to audio. However, I am experiencing issues with the sound coming from the speakers.

The OS looks like that recognizes my sound card, only the sound doesn't go out to the speakers.
